### ISSUE TITLE
Time specification in /export by-date [since]

### ISSUE THREAD

**Issue by katerinabc** [RnDAO/tc-botComm#20]
When using export-by-date the date has to be added in milliseconds. Can this be changed to something human readable. Time could be default 00:00

**Comment by wkarshat** [comment]
/export by-date [since - format?] 

Implementation on branch perhaps addresses the output format.

**Comment by wkarshat** [comment]
Needs specification, validation, and merge.

**Comment by wkarshat** [comment]
Needs specification, validation, and merge.

**Comment by katerinabc** [comment]
Context: The exported data is fed into scripts for time analysis (Ene's scripts). When I opened the issue, he had to convert the UNIX time epoch (milliseconds) to human readable time. This was necessary for analysis that focused on the last 7 days.

Need: 
- The end user (CM) needs to see human readable times
- We should be able to subset the extracted data to only analysis the last 7 days (or last 10 days, or last months). 

I don't know at what time point it is best to convert to human readable time

**Comment by wkarshat** [comment]
Reference card 513 Time Format and Timezone https://app.dework.xyz/rndao-1/research-community/view/board-5394?taskId=b1224fd1-3489-42ba-bb96-3a0c4299d052
