### ISSUE TITLE
export-by-date command: enter human-readable data and not milliseconds since 1970

### ISSUE THREAD

**Issue by katerinabc** [RnDAO/tc-botComm#25]
Context: When running the command `/export-by-date` I need to pick a start date and then convert that date to milliseconds since 01-01-1970. 

Question: Can we change the command so that I can put in a human-readable date and not milliseconds.

**Comment by mehrdadmms** [comment]
Is this task still valid ? 
@katerinabc

**Comment by mehrdadmms** [comment]
This task is not valid anymore
