### ISSUE TITLE
Extract discord roles

### ISSUE THREAD

**Issue by TjitsevdM** [RnDAO/tc-botComm#84]
Description

- every day, the accounts that belong to each discord role need to be added and store in a db

**Comment by TjitsevdM** [comment]
This looks good to me. Maybe as part of creating this dataset, we could also store the total number of members that joined per day. This could be saved in the all_joined field of the memberactivities db.

**Comment by Behzad-rabiei** [comment]
> 1. We need to store accounts who is active in date range.
> 2. This collection updates every day.
> 3. We also need the join date for every user.
> 
> account schema
> 
> ```
> account{
>   "id": SnowFlake,
>   "account": string,
>   "role": Array<string>,
>   "joinDate": Datetime
> }
> ```

Can you add more details for number 2?
What do you mean by updates every day?

**Comment by magicpaIm** [comment]
The account information will be updated everyday as account name or role can be changed.
